### PR TITLE
cast subscription_id to str

### PR DESCRIPTION
**Pull request by ghost**
If subscription_id in the configuration item SUBSCRIPTION_IDS uses unicode a string representation e.g.
SUBSCRIPTION_IDS = [u'ecfb1234-1234-123b-abc0-1234cb90d12f']

the following error message is displayed:

> Scrape failed: Parameter 'subscription_id' must be str.

Debugging the issue, the following traceback is raised:

> Traceback (most recent call last):
>   File "/Users/jweismueller/Coding/venvs/azure-cost-mon/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/Users/jweismueller/Coding/venvs/azure-cost-mon/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/Users/jweismueller/Coding/venvs/azure-cost-mon/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/Users/jweismueller/Coding/venvs/azure-cost-mon/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/Users/jweismueller/Coding/venvs/azure-cost-mon/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/Users/jweismueller/Coding/azure-cost-mon/azure_costs_exporter/views.py", line 70, in metrics
>     content = generate_latest(registry)
>   File "/Users/jweismueller/Coding/venvs/azure-cost-mon/lib/python2.7/site-packages/prometheus_client/exposition.py", line 63, in generate_latest
>     for metric in registry.collect():
>   File "/Users/jweismueller/Coding/venvs/azure-cost-mon/lib/python2.7/site-packages/prometheus_client/core.py", line 97, in collect
>     for metric in collector.collect():
>   File "/Users/jweismueller/Coding/azure-cost-mon/azure_costs_exporter/allocated_vm_collector.py", line 85, in collect
>     self._collect_allocated_vms(allocated_vms)
>   File "/Users/jweismueller/Coding/azure-cost-mon/azure_costs_exporter/allocated_vm_collector.py", line 55, in _collect_allocated_vms
>     compute_client = ComputeManagementClient(self._credentials, subscription_id)
>   File "/Users/jweismueller/Coding/venvs/azure-cost-mon/lib/python2.7/site-packages/azure/mgmt/compute/compute_management_client.py", line 75, in __init__
>     self.config = ComputeManagementClientConfiguration(credentials, subscription_id, base_url)
>   File "/Users/jweismueller/Coding/venvs/azure-cost-mon/lib/python2.7/site-packages/azure/mgmt/compute/compute_management_client.py", line 41, in __init__
>     raise TypeError("Parameter 'subscription_id' must be str.")
> TypeError: Parameter 'subscription_id' must be str

Maybe we should additionaly file a bug report in the azure.mgmt.compute package.

Casting the subscription_id fixes the issue right now.

### CODE REVIEW

**Comment by MathMagique** [comment]
Filing an issue with Azure would be a good idea, but the issue seems already fixed: https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-compute/azure/mgmt/compute/compute_management_client.py#L41

Change done in https://github.com/Azure/azure-sdk-for-python/commit/0489ff9345f8d8f74cd15ec6406a66de6885aff4#diff-433a44198c60035145a426bc490b2538

**Comment by MathMagique** [comment]
Ok, apparently the change is in the Azure SDK code base, but not released yet for some reason. Your workaround makes sense, in this case.

**Comment by ghost** [comment]
Latest release is from 3.0.1 (2017-09-26) , so bugfix is not yet included.

**Review by MathMagique — APPROVED** [review]

**Comment by StephanErb** [comment]
This is also worth a changelog entry.

**Review by StephanErb — APPROVED** [review]

**Comment by ghost** [comment]
There is a pre-release which already contains the bugfix, see 0489ff9#commitcomment-29754231

**Pull request merged**
